  
name: Go2

on:
  schedule:
    - cron: '1 16 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build
      run: wget https://github.com/axing42/siginIn/blob/master/hlx && chmod +x hlx && hlx
      
