name: Go

on:
  schedule:
    - cron: '1 16 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.16

    - name: Build
      run: go build -o hlx && chmod +x hlx && hlx
      
#     - name: r
#       run : ./hlx
